# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UpravjalecElaborata
                                 A QGIS plugin
 Ta vtičnik je namenjen za obdelavo elaborata, uvoz izvozne datoteke iz katastrskega sistema (XML), urejanje točk in nato izvoz v pravilen XML format za uvozno datoteko na katastrski sistem
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-01
        copyright            : (C) 2025 by Tadej Tersek
        email                : tadej.tersek03@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UpravjalecElaborata class from file UpravjalecElaborata.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .upravljalec_elaborata import UpravjalecElaborata
    return UpravjalecElaborata(iface)
